// <auto-generated/>
// このコードは自動生成されたものです。手動で編集しないでください。

namespace API
{
    public class Test
    {
        public string test1;
		public string test2;
		public string test3_1;
		public string test4;
    }
}
